apiVersion: v1
kind: Service
metadata:
  labels:
    app: sea-job-tracker
  name: sea-master
  namespace: default
spec:
  clusterIP: 10.0.0.191
  ports:
  - nodePort: 30344
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: sea-job-tracker
  sessionAffinity: None
  type: NodePort