apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: misaki-master
spec:
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: misaki-master
    spec:
      containers:
      - name: misaki-master
        # Run this image
        image: gcr.io/serval-cat/misaki-master
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 11111
        env:
        - name: ETCD_CLUSTER
          value: "etcd-client:2379"

---

apiVersion: v1
kind: Service
metadata:
  name: misaki-master-svc
spec:
  type: LoadBalancer
  ports:
  - name: misaki-master-port
    port: 80
    protocol: TCP
    targetPort: 11111
  selector:
    app: misaki-master